name: Build with latexmk and publish to release page
on:
  push:
    tags:
      - v*
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Compile thesis.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: thesis.tex
          args:
      - name: Compile presentation.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: presentation.tex
          args:
      - name: Gather build artifacts
        run: mkdir build && cp -r *.pdf docs/* build/
      - name: Publish prerelease to release page
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.get_version.outputs.VERSION }}"
          prerelease: false
          title: "${{ steps.get_version.outputs.VERSION }}"
          files: |
            build/*
